name: Deploy Lenguista

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rebuild Docker Containers
        run: |
          cd /lenguista
          bash restart.sh